name: Deploy to AWS S3
description: Deploy a static website to AWS S3 bucket
inputs:
  bucket:
    description: 'The S3 bucket name.'
    required: true
  bucket-region:
    description: 'The region AWS S3 bucket'
    required: false
    default: eu-central-1
  dist-folder:
    description: 'The folder containing the build files.'
    required: true
outputs:
  website-url:
    description: 'The URL of the deployed website'
runs:
  using: 'docker'
  image: 'Dockerfile'